# This is a generated file. Not intended for manual editing.
services:
  weatherforecast:
    build:
      context: "/Users/faragh/Projects/WebApplication2"
      dockerfile: "WeatherForecast/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "weatherforecast:dev"
    ports:
    - "127.0.0.1:57053:57100"
    - "127.0.0.1:57253:57300"
    volumes:
    - "/Users/faragh/.nuget/packages:/root/.nuget/packages"
    - "/Users/faragh/Projects/WebApplication2/WeatherForecast:/app:rw"
    - "/Users/faragh/Projects/WebApplication2:/src:rw"
    - "/Users/faragh/.local/share/JetBrains/RiderRemoteDebugger/2024.2.1/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/faragh/Library/Logs/JetBrains/Rider2024.2/DebuggerWorker/JetBrains.Debugger.Worker.2024_11_09_00_55_34:/var/opt/rider-debugger:rw"
    working_dir: "/app"
